[workspace]
resolver = "2"
members = [".", "crates/*"]

[workspace.package]
rust-version = "1.92"
authors = ["Zan Baldwin"]
edition = "2024"
license = "MIT"
version = "0.1.0-beta"

[workspace.dependencies]
async-compression = "^0.4.41"
async-stream = "^0.3.6"
async-trait = "^0.1"
blake3 = "^1.8"
brotli = "^8.0"
bzip2 = "^0.6.0"
clap = "^4.5"
console = "^0.16.2"
crc32fast = "^1.5"
derive_more = "^2.1"
dialoguer = { version = "^0.12.0", default-features = false }
directories = "^6.0"
exn = "^0.3"
fast_html2md = "^0.0.58"
figment = "^0.10.19"
flate2 = "^1.1"
futures = { version = "^0.3.30", default-features = false }
html5ever = "^0.39.0"
indicatif = { version = "^0.18.4", default-features = false }
libbzip3-sys = { version = "^0.5", features = ["bundled"] }
liblzma = "^0.4.6"
memchr = "^2.8"
miette = "^7.6"
opendal = { version = "^0.55.0", default-features = false }
pin-project-lite = "^0.2.17"
rawr-asyncutils = { path = "crates/asyncutils", default-features = false }
rawr-cache = { path = "crates/cache", default-features = false }
rawr-compress = { path = "crates/compress", default-features = false }
rawr-config = { path = "crates/config", default-features = false }
rawr-extract = { path = "crates/extract", default-features = false }
rawr-library = { path = "crates/library", default-features = false }
rawr-render = { path = "crates/render", default-features = false }
rawr-storage = { path = "crates/storage", default-features = false }
rawr-xhtml = { path = "crates/xhtml", default-features = false }
regex = { version = "^1.12", default-features = false }
rslug = "^0.3"
rstest = "^0.26"
rust-embed = "^8.11"
scraper = { git = "https://github.com/rust-scraper/scraper", rev = "bca18390fa23e367ba3980e930454f87c6b13131", default-features = false }
serde = "^1.0"
serde_json = "^1.0"
similar = "^2.7"
sqlx = { version = "^0.8.6", default-features = false }
tempfile = "^3.25"
tendril = "^0.5.0"
time = "^0.3.47"
tokio = { version = "^1.49", default-features = false }
tokio-util = { version = "^0.7", default-features = false }
tracing = "^0.1.0"
tracing-subscriber = { version = "^0.3.22", default-features = false }
upon = { version = "^0.10.0", default-features = false }
which = "^8.0"
zstd = "^0.13"

[package]
name = "rawr-cli"
description = "Rawr CLI Tool"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "rawr"
path = "src/main.rs"

[features]
default = ["s3", "pdf", "epub"]
brotli = ["rawr-compress/brotli"]
bzip3 = ["rawr-compress/bzip3"]
xz = ["rawr-compress/xz"]
zstd = ["rawr-compress/zstd"]
_sync = []
s3 = ["_sync", "rawr-storage/s3"]
_render = ["dep:rawr-render"]
pdf = ["_render"]
epub = ["_render"]

[dependencies]
async-stream = { workspace = true }
clap = { workspace = true, features = ["derive"] }
console = { workspace = true }
dialoguer = { workspace = true }
exn = { workspace = true }
futures = { workspace = true, features = ["std"] }
indicatif = { workspace = true, features = ["unicode-width"] }
miette = { workspace = true, features = ["fancy"] }
rawr-cache = { workspace = true }
rawr-compress = { workspace = true, features = ["cli"] }
rawr-config = { workspace = true }
rawr-extract = { workspace = true }
rawr-library = { workspace = true }
rawr-render = { workspace = true, optional = true }
rawr-storage = { workspace = true }
similar = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "fs"] }
tokio-util = { workspace = true, features = ["compat"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = [
    "std",
    "fmt",
    "ansi",
    "env-filter",
] }
