[package]
name = "rawr-render"
description = "Document rendering for AO3 HTML works"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
default = ["epub", "pdf"]
epub = ["dep:epub-builder", "dep:rawr-extract", "rawr-extract/chapters"]
metadata = ["dep:rawr-extract"]
pdf = ["dep:which"]

[dependencies]
derive_more = { workspace = true, features = ["display", "error"] }
epub-builder = { workspace = true, optional = true }
exn = { workspace = true }
rawr-extract = { workspace = true, optional = true }
rslug = { workspace = true }
rust-embed = { workspace = true }
tracing = { workspace = true }
tempfile = { workspace = true }
which = { workspace = true, optional = true }

[dev-dependencies]
rstest = { workspace = true }
time = { workspace = true }
